version: '3.7'

services:

  php:
    container_name: dice-roll-php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./app:/app


networks:
  default:
    name: dice-roll-net